import Header from "@/src/dashboard/Header"
import SideNav from "@/src/dashboard/SideNav"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Reshaped, View } from "reshaped"
import "reshaped/themes/reshaped/theme.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Reshaped theme="reshaped">
          <Header />
          <View.Item columns={12}>
            <SideNav />
              <div className="ml-80">
                {children}
              </div>
            </View.Item>
        </Reshaped>
    </body>
    </html>
  )
}
